test:
	g++ -Wall -o main test.cc -I/usr/local/include -L/usr/local/lib -lgraph
	./main

testMonochrome:
	g++ -Wall -o main testMonochrome.cc -I/usr/local/include -L/usr/local/lib -lgraph
	./main

clean:
	rm -f main
